server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://testdata_user:Sup3rS3cret@localhost:27017/testdata_db?authSource=admin

app:
  sync:
    cron: "0 0/5 * * * *"
  lease:
    minutes: 15
  environments:
    - key: env1
      url: jdbc:sybase:Tds:sybase-host1:5000/db1
      username: user1
      password: pass1
